biolab/orange3-bioinformatics

orangecontrib/bioinformatics/ncbi/gene/__init__.py, orangecontrib/bioinformatics/ncbi/taxonomy/config.py
Add Aplysia californica to the supported organism. Enable gene matching by NCBI IDs.
=> [ENH] Support new organism, improve gene matcher

orangecontrib/bioinformatics/tests/ncbi/test_taxonomy.py, orangecontrib/bioinformatics/tests/test_geneset.py, orangecontrib/bioinformatics/tests/test_geo.py, orangecontrib/bioinformatics/tests/utils/test_gui.py
=> [ENH] Add tests for geo, genesets and taxonomy modules

orangecontrib/bioinformatics/geneset/__init__.py, orangecontrib/bioinformatics/ncbi/gene/config.py, orangecontrib/bioinformatics/ncbi/gene/utils.py, orangecontrib/bioinformatics/ncbi/taxonomy/utils.py, orangecontrib/bioinformatics/utils/__init__.py, orangecontrib/bioinformatics/utils/serverfiles.py, orangecontrib/bioinformatics/widgets/OWDifferentialExpression.py, orangecontrib/bioinformatics/widgets/OWGEODatasets.py, orangecontrib/bioinformatics/widgets/OWGOBrowser.py, orangecontrib/bioinformatics/widgets/OWGeneInfo.py, orangecontrib/bioinformatics/widgets/OWGeneSets.py, orangecontrib/bioinformatics/widgets/OWKEGGPathwayBrowser.py, orangecontrib/bioinformatics/widgets/OWdictyExpress.py, orangecontrib/bioinformatics/widgets/utils/data.py, server_update/__init__.py, server_update/common.py, server_update/tests/test_GEO.py, server_update/updateDictyBase.py, server_update/updateGEO.py, server_update/updateGO.py, server_update/updateGeneInfo.py, server_update/updateGeneMatcher.py, server_update/updateGeneSets.py, server_update/updateTaxonomy.py
Update server scripts so that we include additional tags in .info file.
Load genesets from serverfiles an localfiles.
=> [REF] Change server info schema, so that it can handle locally added files and some code refactoring 

orangecontrib/bioinformatics/widgets/OWDatabasesUpdate.py
Users can now load custom files (for the supported organism) in this widget.
=> [ENH] OWDatabasesUpdate: support for adding custom file, code refractor

orangecontrib/bioinformatics/ncbi/gene/config.py, orangecontrib/bioinformatics/tests/ncbi/test_taxonomy.py, orangecontrib/bioinformatics/widgets/OWdictyExpress.py
=> [FIX] Fix failing tests, handle dictyExpress error on loading annotations from data object

orangecontrib/bioinformatics/ncbi/gene/__init__.py, orangecontrib/bioinformatics/ncbi/gene/config.py, orangecontrib/bioinformatics/ncbi/gene/utils.py, orangecontrib/bioinformatics/utils/serverfiles.py, server_update/updateGeneMatcher.py
Add new tag ([symbol from nomenclature authority](https://www.genenames.org/)) by which you can match gene names from our gene info knowledge base.
Support case-insensitive gene name matching.
=> ncbi: add support for case-insensitive gene name matching

orangecontrib/bioinformatics/tests/widgets/test_OWDifferentialExpression.py, orangecontrib/bioinformatics/widgets/OWDifferentialExpression.py
=> [ENH] OWDifferentialEcpression: Add hypergeometric test

orangecontrib/bioinformatics/widgets/OWGeneSets.py, orangecontrib/bioinformatics/widgets/utils/settings.py
=> [ENH] Implement OrganismContextHandler, human readable category names

orangecontrib/bioinformatics/geneset/utils.py, orangecontrib/bioinformatics/widgets/OWGeneSets.py
=> Replaced [*somelist] notations with Python 3.4 compatible

orangecontrib/bioinformatics/resolwe/__init__.py, orangecontrib/bioinformatics/resolwe/genapi.py, orangecontrib/bioinformatics/resolwe/utils.py, orangecontrib/bioinformatics/widgets/OWdictyExpress.py
Globally installed cache caused problems. Requests to the servers are now wrapped around context manager for request_cache.
=> [FIX] OWdictyExpress: use requests_cache module with contextmanager

orangecontrib/bioinformatics/widgets/OWGEODatasets.py, orangecontrib/bioinformatics/widgets/utils/data.py
=> [ENH] New data attribute, GEO tables now have Gene IDs

orangecontrib/bioinformatics/tests/test_statistics.py, orangecontrib/bioinformatics/utils/statistics.py, orangecontrib/bioinformatics/widgets/OWDifferentialExpression.py
=> OWDifferentialExpression: move hypergeometric test into statistics

orangecontrib/bioinformatics/widgets/OWGeneNameMatcher.py, orangecontrib/bioinformatics/widgets/OWGeneNameMatching.py
Add a flag for case-insensitive matching
=> [ENH] OWGeneNameMatching: case insensitive matching

orangecontrib/bioinformatics/ncbi/gene/config.py, orangecontrib/bioinformatics/widgets/OWGeneNameMatching.py, orangecontrib/bioinformatics/widgets/utils/data.py
=> [FIX] OWGeneNameMatching: handle scenario if Entrez ID exists in domain

orangecontrib/bioinformatics/widgets/OWdictyExpress.py
Fixes #54
On data download add table attributes and match gene name with Entrez ID where possible.
=> [ENH] OWdictyExpress: annotate table on the output and match gene names 

orangecontrib/bioinformatics/widgets/OWGeneNameMatcher.py
Widget crashed when input data Variables did not exist in stored settings. 
Use DomainContextHandler insted of Setting.
=> [FIX] OWGeneNameMatcher: use DomainContextHandler for input options

orangecontrib/bioinformatics/tests/test_statistics.py, orangecontrib/bioinformatics/utils/statistics.py, orangecontrib/bioinformatics/widgets/OWDifferentialExpression.py
Vectorized implementation of Hypegometric test.
=> [WIP] Hypergeom speedup

orangecontrib/bioinformatics/ncbi/gene/__init__.py, orangecontrib/bioinformatics/ncbi/gene/config.py, orangecontrib/bioinformatics/widgets/OWGeneNameMatcher.py
=> [ENH] OWGeneNameMatcher: revision

orangecontrib/bioinformatics/widgets/OWGeneNameMatcher.py, orangecontrib/bioinformatics/widgets/OWGeneSetEnrichment.py
=> [FIX] Do not apply filters if input data is not present.

orangecontrib/bioinformatics/cluster_analysis/__init__.py, orangecontrib/bioinformatics/utils/statistics.py, orangecontrib/bioinformatics/widgets/OWClusterAnalysis.py, orangecontrib/bioinformatics/widgets/OWGeneNameMatcher.py, orangecontrib/bioinformatics/widgets/utils/data.py, orangecontrib/bioinformatics/widgets/utils/gui/__init__.py, orangecontrib/bioinformatics/widgets/utils/gui/gene_scoring.py, orangecontrib/bioinformatics/widgets/utils/gui/gene_sets.py
https://github.com/biolab/orange3-single-cell/issues/229
This is a work in progress, do not merge. Please report bugs.
=> [ENH] OWClusterAnalysis

orangecontrib/bioinformatics/cluster_analysis/__init__.py, orangecontrib/bioinformatics/tests/test_statistics.py, orangecontrib/bioinformatics/utils/statistics.py, orangecontrib/bioinformatics/widgets/OWClusterAnalysis.py, orangecontrib/bioinformatics/widgets/OWDifferentialExpression.py, orangecontrib/bioinformatics/widgets/utils/gui/gene_scoring.py
ClusterAnalysis tests only for one variable and supports only two-tailed tests.
Add additional variable to account for batch effects and allow multiple alternative hypotheses.
=> [ENH] ClusterAnalysis: Batch effects in differential expression and alternative hypotheses

orangecontrib/bioinformatics/widgets/OWGeneSetEnrichment.py
=> [ENH] OWGeneSetEnrichment: use GeneSetsSelection widget from utils.gui

orangecontrib/bioinformatics/widgets/OWDatabasesUpdate.py
Extra empty space at the bottom of the widget.
Remove empty space, redundant controls and set the layout of bottom buttons.
=> Edit layout of Databases Update

orangecontrib/bioinformatics/geneset/config.py, server_update/updateGeneSets.py
Fixes #62 
[Serverfiles](https://orange.biolab.si/serverfiles-bio2/gene_sets/) for gene sets were updated.
=> [FIX] update broken links in gene set enrichment widget

orangecontrib/bioinformatics/ncbi/gene/__init__.py, orangecontrib/bioinformatics/widgets/OWGOBrowser.py
It Fixes #92, but also handles OWGeneNameMatcher.
=> [FIX] ignore internet connection, use local files if available

orangecontrib/bioinformatics/cluster_analysis/__init__.py, orangecontrib/bioinformatics/widgets/OWClusterAnalysis.py, orangecontrib/bioinformatics/widgets/utils/gui/gene_sets.py
Resolves this issue:
https://github.com/biolab/orange3-single-cell/issues/299
=> [ENH] OWClusterAnalysis: add support for multiple discrete variables selection

orangecontrib/bioinformatics/cluster_analysis/__init__.py, orangecontrib/bioinformatics/widgets/OWClusterAnalysis.py, requirements.txt
Fixes #98 
Fix ordering in a newly created Discrete variable.
Implement additional output signals:
=> [ENH] Support for additional output signals in Cluster Analysis widget

doc/widget_data.json
Location of widget icons in `widget_data.json` file are not correct. 
Location of widget icons  in `widget_data.json` updated (hierarchical structure).
=> Widget_data.json icons location updated

orangecontrib/bioinformatics/widgets/OWdictyExpress.py
Widget now remembers selection of experiments.
=> [ENH] OWdictyExpress: minor improvements

orangecontrib/bioinformatics/geneset/utils.py, orangecontrib/bioinformatics/widgets/OWGeneSetEnrichment.py, orangecontrib/bioinformatics/widgets/OWGeneSets.py, orangecontrib/bioinformatics/widgets/utils/gui/gene_sets.py
=> gene sets: new widget, schema only settings, code refactor

orangecontrib/bioinformatics/cluster_analysis/__init__.py, orangecontrib/bioinformatics/widgets/OWClusterAnalysis.py
=> [ENH][FIX]OWClusterAnalysis fixups and enhancements

orangecontrib/bioinformatics/widgets/utils/gui/gene_scoring.py, orangecontrib/bioinformatics/widgets/utils/gui/gene_sets.py
QGroupBox is imported from Orange.widgets.gui. 
Import QGroupBox from QtWidgets
=> [FIX] Fix import of QGroupBox

doc/index.rst, doc/scripting_references/annotation.rst, orangecontrib/bioinformatics/annotation/annotate_samples.py, orangecontrib/bioinformatics/tests/annotation/test_annotate_samples.py, requirements.txt
Implements #124
Added functionality to mark genes with gene types, tests, and documentation.
=> Cell annotations

orangecontrib/bioinformatics/tests/widgets/test_OWGenes.py, orangecontrib/bioinformatics/widgets/OWGenes.py
Improve filtering on genes table
=> [ENH] OWGenes: improve gene filtering

orangecontrib/bioinformatics/annotation/annotate_samples.py, orangecontrib/bioinformatics/tests/annotation/test_annotate_samples.py
Computation of p-value is slow due to looping.
In this PR we replace the calculation of p-value with more efficient implementation.
=> AnnotateSamples: p-value calculation speedup

orangecontrib/bioinformatics/annotation/annotate_projection.py
Concave hull is not smooth enough.
With this PR it is smoother
=> [ENH] Smoother hull

orangecontrib/bioinformatics/tests/widgets/test_OWAnnotateProjection.py, orangecontrib/bioinformatics/widgets/OWAnnotateProjection.py, orangecontrib/bioinformatics/widgets/icons/OWAnnotateProjection.svg
=> OWAnnotateProjection: New widget

orangecontrib/bioinformatics/annotation/annotate_projection.py
Orange will have different implementation of clustering soon. https://github.com/biolab/orange3/pull/3814
With this PR I made a changes in clustering such that it works with old clustering from Orange as well with changes in Orange clustering which will be merged soon.
=> AnnotateProjection: Clustering modified for upcoming changes in Orange

.azure-pipelines/build.yml, .azure-pipelines/test.yml, .coveragerc, README.md, codecov.yml
=> azure-pipelines: update azure pipelines add support for codecov

orangecontrib/bioinformatics/widgets/OWAnnotateProjection.py
=> [FIX] Annotator: Always draw labels above hulls

orangecontrib/bioinformatics/annotation/annotate_projection.py, orangecontrib/bioinformatics/tests/annotation/test_annotate_projection.py
To implement new functionalities of Annotator widget we need a function that assign current clusters to new points.
Implemented a function that gets new points and assigns current clusters to those points based on concave hulls.
=> Annotator: Function to assign current clusters to new points

orangecontrib/bioinformatics/annotation/annotate_projection.py, orangecontrib/bioinformatics/tests/annotation/test_annotate_projection.py
When hull crosses the same point multiple times errors can happen:
- the algorithm never compute the hull since it cycles on the same points
- the algorithm take the shorter path to the end - no all points are included in the hull
Described issues are solved such that the algorithm selects vertices that have a larger angle.
=> [FIX] Annotator: Fix hull to prevent cycling and missed points

orangecontrib/bioinformatics/tests/widgets/test_OWAnnotateProjection.py, orangecontrib/bioinformatics/widgets/OWAnnotateProjection.py
=> [ENH] Annotator: Update

orangecontrib/bioinformatics/annotation/annotate_projection.py, orangecontrib/bioinformatics/tests/annotation/test_annotate_projection.py
Fixes #173 
With this PR we make that cells without labels are not clustered
=> Annotator: Cells without cell type assigned should not be clustered

orangecontrib/bioinformatics/ncbi/gene/__init__.py, orangecontrib/bioinformatics/ncbi/homologene/__init__.py, orangecontrib/bioinformatics/tests/widgets/test_OWHomologs.py, orangecontrib/bioinformatics/widgets/OWHomologs.py, orangecontrib/bioinformatics/widgets/OWHomology.py
Match(by rows) genes between two different organism.
=> [ENH] Homology widget

orangecontrib/bioinformatics/widgets/OWHomologs.py
=> [FIX] OWHomologs: update warning messages.

orangecontrib/bioinformatics/geo/config.py, orangecontrib/bioinformatics/widgets/OWGEODatasets.py
Fixes #174
Fixes #175 
Columns are now sorted in alphabetical and/or numerical order. Depending on the data sotred in columns. Widget now handles even sorting by GDS ID. See example below.
=> [FIX] Properly handle row sorting 

orangecontrib/bioinformatics/kegg/api.py, orangecontrib/bioinformatics/kegg/brite.py, orangecontrib/bioinformatics/kegg/caching.py, orangecontrib/bioinformatics/kegg/conf.py, orangecontrib/bioinformatics/kegg/databases.py, orangecontrib/bioinformatics/kegg/pathway.py, orangecontrib/bioinformatics/tests/kegg/test_api.py, orangecontrib/bioinformatics/tests/kegg/test_databases.py, orangecontrib/bioinformatics/tests/kegg/test_entry.py
=> test: fix kegg tests

.azure-pipelines/install_addon.yml, .azure-pipelines/jobs.yml
=> azure-pipelines: fix corrupted numpy build

orangecontrib/bioinformatics/widgets/OWMarkerGenes.py
Fixes #156 
If there are no genes selected, all currently displayed genes are sent on output.
=> [FIX] OWMarker_gene: If there are no genes selected, send all genes on output.

orangecontrib/bioinformatics/annotation/annotate_samples.py, orangecontrib/bioinformatics/tests/annotation/test_annotate_samples.py, orangecontrib/bioinformatics/tests/widgets/test_OWAnnotateProjection.py, orangecontrib/bioinformatics/widgets/OWAnnotateProjection.py, setup.py
The annotation is now implemented as an external library.
Embed an external library in for annotation.
=> Annotator moved to the external library

orangecontrib/bioinformatics/tests/widgets/test_OWAnnotateProjection.py
Merge proposed by #196 was bad and caused tests to start failing.
Wrong changes in this merge are undone with this PR.
=> [FIX] TestOWAnnotateProjection: fix failing tests

CHANGELOG.md, orangecontrib/bioinformatics/widgets/OWGeneSets.py
Wrong column data in OWGeneSets widget
=> [FIX] OWGeneSets: fix wrong column order

CHANGELOG.md, orangecontrib/bioinformatics/widgets/OWMarkerGenes.py
=> [FIX] OWMarkerGenes: properly handle network errors and use cached files if possible.

CHANGELOG.md, orangecontrib/bioinformatics/geo/__init__.py, orangecontrib/bioinformatics/widgets/OWGEODatasets.py
=> [FIX] OWGEODatasets: properly handle network errors and use cached files if possible.

CHANGELOG.md, orangecontrib/bioinformatics/annotation/annotate_samples.py, orangecontrib/bioinformatics/tests/annotation/test_annotate_samples.py, orangecontrib/bioinformatics/widgets/OWAnnotateProjection.py, setup.py
`cellannotation` is now `point-annotator`
The package has been changed
=> Replace cellannotation package with pointannotator

orangecontrib/bioinformatics/annotation/annotate_samples.py, orangecontrib/bioinformatics/tests/annotation/test_annotate_samples.py
Annotator does not work when cell type or entrez id is disrete (not string) and when any of them is features instead of meta.
With this PR we fix annotator such that all combinations of locations and variable types of Entrez ID/cell types work.
=> AnnotateSamples: Accept marker genes with different variables types

orangecontrib/bioinformatics/widgets/icons/OWHomologs.svg
=> [ENH] Homologs icon

orangecontrib/bioinformatics/tests/widgets/test_OWGEODatasets.py, orangecontrib/bioinformatics/widgets/OWGEODatasets.py
Fixes #210
Check if numpy array in the model is empty before sorting. Add additional tests.
=> [FIX] OWGEODatasets: fix sort on empty array

orangecontrib/bioinformatics/tests/widgets/test_OWAnnotateProjection.py
Fix tests after https://github.com/biolab/orange3/pull/4219
=> ConcurrentWidgetMixin: Cancel task on input change

orangecontrib/bioinformatics/tests/widgets/test_OWAnnotateProjection.py
Reverts biolab/orange3-bioinformatics#220
=> Revert "ConcurrentWidgetMixin: Cancel task on input change"

orangecontrib/bioinformatics/tests/widgets/test_OWMarkerGenes.py, orangecontrib/bioinformatics/widgets/OWMarkerGenes.py, orangecontrib/bioinformatics/widgets/utils/settings.py
#180 
Redesign of the marker genes widget.
=> [ENH] Marker genes widget redesign

orangecontrib/bioinformatics/widgets/OWGOBrowser.py, orangecontrib/bioinformatics/widgets/OWGeneSetEnrichment.py, orangecontrib/bioinformatics/widgets/OWGeneSets.py
=> [FIX] enrichment: actually use whole genome for reference genes

README.pypi
Implements https://github.com/biolab/orange3/issues/4850
Unify add-on descriptions.
=> Unify add-on descriptions

orangecontrib/bioinformatics/preprocess/__init__.py, orangecontrib/bioinformatics/preprocess/normalize.py, orangecontrib/bioinformatics/resolwe/__init__.py, orangecontrib/bioinformatics/resolwe/genapi.py, orangecontrib/bioinformatics/resolwe/resapi.py, orangecontrib/bioinformatics/resolwe/utils.py, orangecontrib/bioinformatics/widgets/OWGenialisExpressions.py, orangecontrib/bioinformatics/widgets/icons/OWGenialisExpressions.svg, setup.py
Fixes #250
Fixes #249
Fixes #248
Fixes #247
=> [ENH] Genialis Expressions widget

orangecontrib/bioinformatics/preprocess/normalize.py, orangecontrib/bioinformatics/tests/preprocess/test_normalize.py, orangecontrib/bioinformatics/widgets/OWGenialisExpressions.py, setup.py
=> [ENH] GenialisExpression: add quantile transform 

orangecontrib/bioinformatics/widgets/OWGenialisExpressions.py
https://github.com/biolab/orange3-bioinformatics/issues/256#issuecomment-671187980
=> Raise warning on collections with different data feature types

orangecontrib/bioinformatics/preprocess/normalize.py, orangecontrib/bioinformatics/tests/preprocess/test_normalize.py
Follow the implementation of quantile normalization found at https://github.com/genialis/rnaseq-normalization
When 'https://github.com/genialis/rnaseq-normalization/pull/9' is merged we should use their implementation.
=> [FIX] preprocess: fix quantile normalization

orangecontrib/bioinformatics/tests/widgets/components/test_GeneSetSelection.py, orangecontrib/bioinformatics/tests/widgets/test_OWGEODatasets.py, orangecontrib/bioinformatics/tests/widgets/test_OWGeneSets.py, orangecontrib/bioinformatics/tests/widgets/test_OWGenes.py, orangecontrib/bioinformatics/tests/widgets/test_OWGenialisExpressions.py, orangecontrib/bioinformatics/tests/widgets/test_OWHomologs.py, orangecontrib/bioinformatics/tests/widgets/test_OWMarkerGenes.py, tox.ini
Failing CI checks
- import WidgetTest and GuiTest from orange-widget-base package
- Disable pip check in tox configuration due to: https://github.com/pypa/virtualenv/pull/1953
=> [FIX] Failing CI checks

orangecontrib/bioinformatics/resolwe/resapi.py
We use the requests-cache module to store responses from frequently accessed endpoints. 
To make cached key session aware one should use include_get_headers. This is a problem since on every login session-id changes and makes previously-stored responses invalid.
To solve this problem we remove include_get_headers flag. We must then disable caching on requests that should return data based on currently provided credentials.
Additionally, we increase cache_expire to 365 days.
=> [FIX] resapi: make requests cache available even when sesion id changes (new login)

orangecontrib/bioinformatics/preprocess/normalize.py, orangecontrib/bioinformatics/widgets/OWGenialisExpressions.py
https://github.com/biolab/genialis/issues/1
=> OWGenialisExpression: use number of samples/genes as quantiles in QuantileTransform

orangecontrib/bioinformatics/widgets/OWGenialisExpressions.py
https://github.com/biolab/genialis/issues/5
=> OWGenialisExpression: show gene matcher report

orangecontrib/bioinformatics/resolwe/resapi.py, orangecontrib/bioinformatics/resolwe/sample_metadata.py, orangecontrib/bioinformatics/tests/resolwe/test_sample_metadata.py, orangecontrib/bioinformatics/widgets/OWGenialisExpressions.py
=> [ENH] Fetch sample metadata

.github/workflows/release.yml
=> ci: use pypa build project for building dist files [skip ci]

.github/workflows/test.yml, orangecontrib/bioinformatics/resolwe/__init__.py, orangecontrib/bioinformatics/resolwe/genapi.py, orangecontrib/bioinformatics/resolwe/utils.py, orangecontrib/bioinformatics/widgets/OWdictyExpress.py, tox.ini
=> [ENH] OWdictyExpress: use CredentialManager and ConcurrentWidgetMixin

orangecontrib/bioinformatics/widgets/OWKEGGPathwayBrowser.py
Fixes gh-95
Map selection gene ids between kegg and ncbi ids for selection.
=> [FIX] OWKEGGPathwayBrowser: Fix selection

.pre-commit-config.yaml, orangecontrib/bioinformatics/widgets/OWGenialisExpressions.py, setup.py
=> [ENH] Add QC data to Genialis Expression widget

orangecontrib/bioinformatics/kegg/__init__.py, orangecontrib/bioinformatics/kegg/databases.py
Fixes: gh-302
Explicitly try to map essential and common organisms.
=> kegg: Fix `kegg.from_taxid` mapping due to change in api search results

orangecontrib/bioinformatics/widgets/OWGenialisExpressions.py
=> [FIX] Owgenialisexpressions: fix sign in dialog, remove info box, use defered commit

orangecontrib/bioinformatics/tests/widgets/test_OWGEODatasets.py, orangecontrib/bioinformatics/widgets/OWGEODatasets.py, orangecontrib/bioinformatics/widgets/utils/itemmodels.py
Fixes gh-306, Fixes gh-305 (with https://github.com/biolab/orange-widget-base/pull/216)
Also reduces memory consumption of the widget.
Rework GEO datasets model, avoid PyTableModel.
=> [FIX] Rework GEO datasets model

orangecontrib/bioinformatics/widgets/OWSingleSampleScoring.py, orangecontrib/bioinformatics/widgets/utils/__init__.py, setup.py
=> [ENH] OWSingleSampleScoring: add a new widget

orangecontrib/bioinformatics/widgets/OWGeneSetEnrichment.py
=> [FIX] OWGeneSetEnrichment: fix icon path

orangecontrib/bioinformatics/widgets/OWSingleSampleScoring.py
=> [FIX] OWSingleSampleScoring: fix icon path

.github/workflows/rebase.yml
Add automatic rebase with /rebase comment
=> CI - Automatic rebase

orangecontrib/bioinformatics/resolwe/utils.py
=> resolwe.utils: time as column name for Dicty express data

.github/workflows/lint.yml, .pre-commit-config.yaml, orangecontrib/bioinformatics/annotation/annotate_samples.py, orangecontrib/bioinformatics/geo/__init__.py, orangecontrib/bioinformatics/ncbi/gene/__init__.py, orangecontrib/bioinformatics/ncbi/gene/config.py, orangecontrib/bioinformatics/tests/annotation/test_annotate_samples.py, orangecontrib/bioinformatics/tests/widgets/test_OWAnnotateProjection.py, orangecontrib/bioinformatics/tests/widgets/test_OWGenes.py, orangecontrib/bioinformatics/tests/widgets/test_OWHomologs.py, orangecontrib/bioinformatics/tests/widgets/test_OWMarkerGenes.py, orangecontrib/bioinformatics/widgets/OWAnnotateProjection.py, orangecontrib/bioinformatics/widgets/OWClusterAnalysis.py, orangecontrib/bioinformatics/widgets/OWDatabasesUpdate.py, orangecontrib/bioinformatics/widgets/OWDifferentialExpression.py, orangecontrib/bioinformatics/widgets/OWGOBrowser.py, orangecontrib/bioinformatics/widgets/OWGeneSetEnrichment.py, orangecontrib/bioinformatics/widgets/OWGeneSets.py, orangecontrib/bioinformatics/widgets/OWGenes.py, orangecontrib/bioinformatics/widgets/OWHomologs.py, orangecontrib/bioinformatics/widgets/OWKEGGPathwayBrowser.py, orangecontrib/bioinformatics/widgets/OWMarkerGenes.py, orangecontrib/bioinformatics/widgets/OWVolcanoPlot.py, orangecontrib/bioinformatics/widgets/OWdictyExpress.py, orangecontrib/bioinformatics/widgets/components/gene_set_selection.py, orangecontrib/bioinformatics/widgets/utils/gui/label_selection.py, setup.cfg, setup.py, tox.ini
=> [FIX] Fix tests and lint

orangecontrib/bioinformatics/widgets/OWDifferentialExpression.py
=> OWDifferentialExpression: fix data inputs and outputs
