orangecontrib/bioinformatics/widgets/OWGEODatasets.py
orangecontrib/bioinformatics/widgets/OWGOBrowser.py
orangecontrib/bioinformatics/widgets/OWGeneInfo.py
orangecontrib/bioinformatics/widgets/OWGeneSets.py
orangecontrib/bioinformatics/widgets/OWKEGGPathwayBrowser.py
orangecontrib/bioinformatics/widgets/OWdictyExpress.py
server_update/updateGeneMatcher.py

DataHintsCache is used for storing information on gene names location and organism.
A simpler solution is to use attributes in Orange.data.Table

[REF] use Table attributes insted of DataHintsCache

---

orangecontrib/bioinformatics/widgets/utils/gui/label_selection.py

OWDifferentialExpression crashes if the variable attribute is not a string.
When grouping column candidates, read attribute value as a string.

[FIX] gui: always read attribute value as string

---

orangecontrib/bioinformatics/ncbi/gene/__init__.py
orangecontrib/bioinformatics/tests/ncbi/test_gene.py

GeneMatcher didn't properly do case-insensitive name matching.
When the case_insensitive flag is passed to the GeneMatcher object it now converts gene.input_name toto lowercase before matching.

[FIX] gene: fix case-insensitive matching

---

orangecontrib/bioinformatics/geneset/utils.py
orangecontrib/bioinformatics/go/__init__.py
orangecontrib/bioinformatics/widgets/OWGOBrowser.py
orangecontrib/bioinformatics/widgets/OWGeneSets.py
orangecontrib/bioinformatics/widgets/OWKEGGPathwayBrowser.py
orangecontrib/bioinformatics/widgets/utils/data.py
orangecontrib/bioinformatics/widgets/utils/settings.py

Remove Gene name matching process from widgets. All gene name matching will go trough GeneNameMatcher widget.
Remove organism and gene name selection from widget control area.

[ENH] Assume annotated tables when loading data in widgets

---

orangecontrib/bioinformatics/widgets/utils/settings.py

Fixes #120.
If this is not accepted before https://github.com/biolab/orange3/pull/3697, add-on will stop working.
Accepting it before the new release of Orange should not cause any problems.

 SetContextHandler.settings_to_widget: Add argument *args

---

.travis.yml

Travis tests fails due to qt issues.
PyQt locked to version 5.11.3

Lock PyQt version for travis

---

orangecontrib/bioinformatics/annotation/annotate_samples.py
orangecontrib/bioinformatics/tests/annotation/test_annotate_samples.py

It seems some datasets (like AML) has int entre IDs. AnnotateSamples expected them to be strings.
With this PR AnnotateSamples will work for int Entrez IDs too.

[FIX] AnnotateSamples: Adopt for int entrez ID in dataset

---

orangecontrib/bioinformatics/annotation/annotate_samples.py

TAX_ID does not need to be an argument since it is already present in data argument.
TAX_ID argument removed

Removed TAX_ID argument from assign_annotations function

---

doc/index.rst
doc/scripting_references/annotation.rst
orangecontrib/bioinformatics/annotation/annotate_projection.py
orangecontrib/bioinformatics/tests/annotation/test_annotate_projection.py
requirements.txt

Implements #125
This script:
- Clusters the projections
- Assigns annotations to clusters
- Computes annotation locations at the projection
- Computes the concave hull around clusters
Note: Because of efficiency of hull computation the `shapely` dependency is added to the project.

Annotate projection

---

orangecontrib/bioinformatics/annotation/annotate_projection.py
orangecontrib/bioinformatics/tests/annotation/test_annotate_projection.py

Function annotate_projection projection change to return:
- clusters 
- metadata for clusters (labels, positions for placing the labels, concave hull)
- eps - epsilon used in clustering and hull computation

annotate_projection returns hull and epsilon

---

orangecontrib/bioinformatics/annotation/annotate_samples.py
orangecontrib/bioinformatics/tests/annotation/test_annotate_samples.py

Before values that have higher p-value with threshold were filtered out with 0.
It is not a good practice since zero has meaning when scoring is log(FDR) or log(P-value).
This PR changes filtering out to use nans instead of 0.

AnnotateSamples: Filter values that have higher p-value with nan

---

orangecontrib/bioinformatics/tests/annotation/test_annotate_projection.py

Some tests were comented out due to error in DBSCAN in Orange 3. 
Since the new release of Orange is available tests are updated.

[FIX] Annotator: Tests updated after Orange3 release

---

.azure-pipelines/install_addon.yml
azure-pipelines.yml
orangecontrib/bioinformatics/annotation/annotate_projection.py
orangecontrib/bioinformatics/tests/annotation/test_annotate_projection.py
orangecontrib/bioinformatics/tests/widgets/test_OWAnnotateProjection.py
requirements.txt

Fixes https://github.com/biolab/orange3-bioinformatics/issues/152
Shapely was replaced with pyclipper which makes buffering (make an offset of the polygon-hull) and part of the Shapely's task (joining triangles in polygon) is made manually now.
Pyclipper is also c/cyton based library but has all wheels available - for Windows too.
In this pull request, I also increase the wait time in one of the tests or the Annotator widget. It was required since this test usually failed due to time out. I found out that this is not connected with changes in this PR. This test kept failing before changes.

Annotator: Remove shapely

---

orangecontrib/bioinformatics/annotation/annotate_projection.py
orangecontrib/bioinformatics/tests/annotation/test_annotate_projection.py

Assigning new points to clusters does not work corectly - error in array concatenation.
Use np.conatenate for concatenating arrays

[FIX] Annotator: Merge np arrays with concatenate

---

orangecontrib/bioinformatics/annotation/annotate_projection.py

Since label locations were computed as a cluster mean they were not exactly in the center of the cluster.
Location is now computed as an average of max and min value of the cluster.

[FIX] OwAnnotator: Fix label locations to be in the center of the cluster

---

orangecontrib/bioinformatics/annotation/annotate_projection.py

Annotator faild to copute the clustering epsilone when not enough data items present.
Compute epsilon on the smaller neighborhood when not enough data.

[FIX] OWAnnotator: Compute epsilon with smaller k when not enough data items.

---

orangecontrib/bioinformatics/annotation/annotate_samples.py

When somone connect wrong data to the annontator (e.g. PCA data) the error message is not clear.
Added assert which checks whether there is Entrez ID in any of column.

Annotator: Added check if input data has gene expressions

---

orangecontrib/bioinformatics/tests/widgets/test_OWAnnotateProjection.py

Widget tests for Annotator widget have been extremely slow. 
Since the functions (`annotate_samples` and `annotate_projection`) the widget is using are already tested in separate unit tests, they are left out in widget testing and replaced with dummy ones.

Annotator: Widget tests speedup

---

orangecontrib/bioinformatics/ncbi/gene/__init__.py
orangecontrib/bioinformatics/widgets/OWGenes.py

The "Genes" widget is slow. While the gene matching happens in a separate thread, `commit` still runs on the GUI thread. Unfortunately, `commit` is slow, and freezes everything for a while when dealing with large numbers of genes.
Running the profiler, I quickly found out that list comprehensions of the form `[... for gene in genes if g in <something>]` where "something" was a long list. List lookups are slow, so replacing these with `set` instances sped up things dramatically.
E.g. the runtime for [xin2016 sample](http://file.biolab.si/scdata/xin2016_pancreas_human_sample.tab.gz) is reduced from ~45sec to ~7sec.
Obviously, ideally, we would have all this more compute-heavy code run in a separate thread, but that would require a bit more effort.

[ENH] OWGenes: Speed up commit

---

orangecontrib/bioinformatics/annotation/annotate_samples.py
orangecontrib/bioinformatics/tests/annotation/test_annotate_samples.py
setup.py

Annotator do not support sparse data. 
Breaking changes in point-annotator 2.0.0
- Switching to point-annotator 2.0.0
- Supporting sparse data tables
- Tests for sparse data

[ENH] Point-annotator 2.0.0 and support for sparse data

---

orangecontrib/bioinformatics/widgets/OWdictyExpress.py

[FIX] OWdictyExpress: use match_table_column from gene matcher module.

---

orangecontrib/bioinformatics/tests/widgets/test_OWAnnotateProjection.py
orangecontrib/bioinformatics/tests/widgets/test_OWGenes.py

Tests starts to fail due to changes in ConcurrentWidgetMixin
On places where ConcurrentWidgetMixin is used `wait_until_stop_blocking` replaced by `wait_until_finished`

Fix tests due to changes in WidgetTest

---

orangecontrib/bioinformatics/tests/annotation/test_annotate_projection.py
orangecontrib/bioinformatics/tests/widgets/test_OWAnnotateProjection.py
orangecontrib/bioinformatics/widgets/OWAnnotateProjection.py

Annotator failed on creating the output and on coloring based on cluster.
- fixing palette for colour by cluster
- the redundant parameter on the function that creates output removed 
- replacing deprecated calls

[FIX] Annotator: fix palette and output

---

orangecontrib/bioinformatics/widgets/OWGEODatasets.py

Fixes gh-239
Remove `wrap` reimplementation, it seems to be just a copy of base implementation before https://github.com/biolab/orange3/pull/4474

[FIX] OWGEODatasets: Remove `wrap` reimplementation

---

orangecontrib/bioinformatics/tests/widgets/test_OWMarkerGenes.py
orangecontrib/bioinformatics/widgets/OWMarkerGenes.py
orangecontrib/bioinformatics/widgets/utils/settings.py

- changed settings of the widget were not migrated when the user opened older workflow
- test started to fail since marker genes data changed
- Added settings migration
- Test updated to be data change independent

[FIX] Marker genes: settings migration

---

orangecontrib/bioinformatics/tests/widgets/test_OWAnnotateProjection.py

Test started to fail since arrays have different shapes
Also, compare shapes

[FIX] AnnotateProjection: fix tests that fail due to changes in numpy

---

orangecontrib/bioinformatics/widgets/OWGenialisExpressions.py

[FIX] OWGenialisExpressions: prevent full text search component to move on animation toggle

---

orangecontrib/bioinformatics/ncbi/gene/__init__.py
orangecontrib/bioinformatics/tests/ncbi/test_gene.py
orangecontrib/bioinformatics/widgets/OWGenialisExpressions.py
orangecontrib/bioinformatics/widgets/OWdictyExpress.py

[ENH] Add option to automatically rename table attributes when matching genes with match_table_attributes

---

orangecontrib/bioinformatics/resolwe/__init__.py
orangecontrib/bioinformatics/widgets/OWGenialisExpressions.py

Control area extended with additional filtering options, see image below.

[ENH] OWGenialisExpression: additionally, filter data objects by process type and input annotations

---

doc/_static/custom.css
doc/conf.py
orangecontrib/bioinformatics/widgets/__init__.py
setup.py

While ago we discussed that we will use the same documentation theme for add-ons. After some discussion, we decided on sphinx-rtd-theme. The alternative is Alabaster but its sidebar is not so readable and it breaks long addon names in two lines.
With this PR I am implementing the sphinx-rtd-theme. I also changed that the menu bar collapses on the medium screen already (before it collapsed on small screens). On the medium screen, the content column was narrow already and it works well for widget documentation in Orange since at the default Orange help window size the sidebar is collapsed.

Change the documentation theme to sphinx_rtd_theme

---

orangecontrib/bioinformatics/tests/kegg/test_databases.py
orangecontrib/bioinformatics/tests/widgets/test_OWMarkerGenes.py
orangecontrib/bioinformatics/widgets/OWMarkerGenes.py
setup.py
tox.ini

Tests started to fail due to adding summaries in widget base
- Removes summaries in marker genes
- Tests still failing but they will be fixed in https://github.com/biolab/orange-widget-base/pull/150.

[FIX] Adjust for changes in widget auto-summary process

---

orangecontrib/bioinformatics/widgets/OWAnnotateProjection.py

The widget crashes because the parents commit method is decorated with `gui.deferred`.
- change `self.commit()` to `self.commit.deferred()`

Annotate Projection: Fix commit invoke

---

orangecontrib/bioinformatics/kegg/caching.py
orangecontrib/bioinformatics/ncbi/taxonomy/utils.py
orangecontrib/bioinformatics/widgets/OWDatabasesUpdate.py

A number of error when running with python 3.10
* Replace use of ABCs from `collections` with `collections.abc`
* Fix an implicit float->int conversion error.

[FIX] Fix compatibility with Python 3.10

---

.github/workflows/test.yml
orangecontrib/bioinformatics/geo/__init__.py
orangecontrib/bioinformatics/ncbi/gene/__init__.py
orangecontrib/bioinformatics/preprocess/normalize.py
orangecontrib/bioinformatics/tests/annotation/test_annotate_projection.py
orangecontrib/bioinformatics/tests/annotation/test_annotate_samples.py
orangecontrib/bioinformatics/tests/ncbi/test_taxonomy.py
orangecontrib/bioinformatics/tests/widgets/test_OWAnnotateProjection.py
orangecontrib/bioinformatics/widgets/OWAnnotateProjection.py
orangecontrib/bioinformatics/widgets/OWGenes.py
orangecontrib/bioinformatics/widgets/OWHomologs.py
setup.py
tox.ini

Annotator use colorpalette which is deprecated https://github.com/biolab/orange3/pull/6135
Because of changes in Orange (mostly Table lock), some widgets/tests do not work.
Use colorpalettes module instead
Necessary fixes for widgets/tests to work:
- handle table locking where necessary
- changing `effective_data` to match other widgets (and I think it is now more correct than before). It was necessary to fix it due to a failing test caused by the change in core Orange. If I understand effective_data correctly, are those data currently plotted as x and y, and if they do not change, replot is unnecessary.

[FIX] Replace colorpalette and other necessary fixes

---

.pre-commit-config.yaml
orangecontrib/bioinformatics/widgets/components/gene_set_selection.py
orangecontrib/bioinformatics/widgets/utils/gui/gene_sets.py

[FIX] QtCore.Qt.ItemIsTristate is deprecated. Use ItemIsUserTristate instead

---

orangecontrib/bioinformatics/annotation/annotate_projection.py
setup.py

Delaunay attribute vertices was deprecated since Scipy version 0.12.0 in favour of simplices and it was finally removed in version 1.11.0.

[FIX] annotate_projection: Delaunay attribute 'vertices' deprecated in favour of 'simplices'

---

orangecontrib/bioinformatics/widgets/OWGeneSetEnrichment.py
orangecontrib/bioinformatics/widgets/utils/gui/__init__.py

Fixes #332 
Also fixes sorting that did not work when you clicked on the column in Gene Set Enrichment widget.
I changed the code so that it sorts the proxy model, not the source model. I also changed the code so that the widget loads the gene sets based on the organism of the input data.

GSEA: sorting and organism bug

---

orangecontrib/bioinformatics/geo/__init__.py

Modified init.py file to correctly categorize the GEO Data Sets variables as discrete variables not as string variables.

[FIX] GEO data sets: fix categorization of variables

---

orangecontrib/bioinformatics/resolwe/utils.py
orangecontrib/bioinformatics/widgets/OWdictyExpress.py

When trying to use dictyExpress as a data source to compare the new data with published data, there is an error. The problem seems to be that the Time column is a String Variable and therefore its PCA cannot be applied to newer data. Editing the domain (so that Time is numeric variable) doesn't seem to fix the issue. Here is a screenshot of the problem.
I propose changing the code so that Time is set as a ContinuousVariable. I also fixed the bug that prevented the dictyExpress from loading (if isinstance(type(row[label[0]]["value"]), list): --> if isinstance(row[label[0]]["value"], list):).

[FIX] dictyExpress: Time as ContinuousVariable

---

.github/workflows/release.yml

[CI] Replace release workflow with reusable one

---

doc/widgets/marker_genes.md
orangecontrib/bioinformatics/tests/widgets/test_OWMarkerGenes.py
orangecontrib/bioinformatics/widgets/OWMarkerGenes.py

This pull request adds DictyBase to the Marker Genes widget. It also adds Milestones and Regulon Clusters to the Group by category. Also edits the documentation and respective unit tests.

Marker Genes: Add DictyBase

---

orangecontrib/bioinformatics/widgets/OWClusterAnalysis.py
orangecontrib/bioinformatics/widgets/utils/gui/__init__.py

Fixes #339.
Addresses various bugs, including issues with score display, and replaces the 'Gene Sets' and 'Custom Gene Sets' boxes with a 'Gene Selection' component.

Cluster analysis: Fix bugs and use of Gene Selection Component
